diet_data_list = [{'diet_name': 'Дієта № 1',
                   'indications': 'гострі захворювання верхніх відділів травного каналу, які тривають протягом 1— 3 міс., або хронічні захворювання, що загострилися (езофагіт), гастрит з підвищеною або нормальною кислотністю, дуоденіт, виразкова хвороба шлунка та дванадцятипалої кишки у фазі помірного загострення.',
                   'purpose': 'Сприяння загоюванню виразок шлунка та дванадцятипалої кишки, ліквідації запальних процесів у верхніх відділах травного каналу.',
                   'excluded_foods': 'страви, що довго затримуються в шлунку та подразнюють його (тваринні жири, рослинна клітковина), стимулятори шлункової секреції, гострі страви, прянощі, міцні бульйони, гриби, бобові, кава, шоколад, какао.',
                   'restricted_foods': 'кухонна сіль, молочнокислі продукти.',
                   'eating_regime': 'Дієта передбачає харчування 6- 7 разів на день через кожні 2-3 год. невеликими порціями. Більша кількість їжі припадає на 1-й, 2-й сніданок та обід. Страви повинні бути механічно подрібненими, вареними, протертими, пареними.',
                   'recommended_foods': 'слизисті супи з круп (вівсяної, гречаної, рисової, манної), молоко, вершки, свіжа нежирна сметана, яловичі, телячі, рибні парові котлети, тефтелі, протерті каші, варені яйця, киселі з ягід та фруктів, розведені соки з них, хліб білий учорашньої випічки.'},
                  {'diet_name': 'Дієта № 1 а',
                   'indications': 'загострення виразкової хвороби шлунка та дванадцятипалої кишки (перші 3-7 днів), загострення гастриту з надмірною кислотністю, опік стравоходу чи шлунка',
                   'purpose': 'Сприяння загоюванню виразок шлунка та дванадцятипалої кишки, ліквідації запальних процесів у верхніх відділах травного каналу під час загострення',
                   'excluded_foods': 'страви, що довго затримуються в шлунку та подразнюють його (тваринні жири, рослинна клітковина), стимулятори шлункової секреції, гострі страви, прянощі, міцні бульйони, гриби, бобові, кава, шоколад, какао',
                   'restricted_foods': 'кухонна сіль, молочнокислі продукти',
                   'eating_regime': 'Дієта передбачає харчування 6-7 разів на день через кожні 2-3 год невеликими порціями. Більша кількість їжі припадає на 1-й, 2-й сніданок та обід',
                   'general_characteristics': 'Страви повинні бути рідкими або напіврідкими зі зменшеною калорійністю. Хворим дають багато вершків, молока, не круто зварені яйця (щоденно), молочні киселі',
                   'recommended_foods': 'слизисті супи з круп (вівсяної, гречаної, рисової, манної), молоко, вершки, свіжа нежирна сметана, яловичі, телячі, рибні парові котлети, тефтелі, протерті каші, варені яйця не круто, киселі з ягід та фруктів, розведені соки з них, хліб білий учорашньої випічки'},
                  {'diet_name': 'Дієта № 1 б',
                   'indications': 'загострення виразкової хвороби шлунка та дванадцятипалої кишки (перші 10-20 днів), загострення хронічного гастриту (перші 7-10 днів)',
                   'purpose': 'Сприяння загоюванню виразок шлунка та дванадцятипалої кишки, ліквідації запальних процесів у верхніх відділах травного каналу під час загострення',
                   'excluded_foods': 'страви, що довго затримуються в шлунку та подразнюють його (тваринні жири, рослинна клітковина), стимулятори шлункової секреції, гострі страви, прянощі, міцні бульйони, гриби, бобові, кава, шоколад, какао',
                   'restricted_foods': 'кухонна сіль, молочнокислі продукти',
                   'eating_regime': 'Дієта передбачає харчування 6-7 разів на день через кожні 2-3 год невеликими порціями. Більша кількість їжі припадає на 1-й, 2-й сніданок та обід',
                   'recommended_foods': 'слизисті супи з круп (вівсяної, гречаної, рисової, манної), молоко, вершки, свіжа нежирна сметана, яловичі, телячі, рибні парові котлети, тефтелі, протерті каші, варені яйця, киселі з ягід та фруктів, розведені соки з них, хліб білий учорашньої випічки, сухарі з білого хліба, протертий нежирний сир, парові тефтелі з телятини, фруктові киселі'},
                  {'diet_name': 'Дієта № 2',
                   'indications': 'гострий гастрит зі зниженою кислотністю, хронічний гастрит зі зниженою кислотністю у фазі загострення, період реконвалесценції після ентериту, коліту',
                   'purpose': 'підвищення секреції шлунка, підвищення секреторної активності інших травних залоз, покращення моторної функції шлунка та кишок',
                   'excluded_foods': "бобові, гриби, жирні сорти м'яса (гусятина, качатина, свинина, баранина), смажені страви",
                   'restricted_foods': 'свіже молоко, вершки, сметана, тваринний жир',
                   'eating_regime': 'дроблене харчування 5-6 разів на день',
                   'recommended_foods': "хліб білий учорашньої випічки, супи круп'яні (крім пшона) на знежиреному м'ясному або рибному бульйоні, відварні м'ясо (яловичина, телятина, курятина) та риба нежирних сортів або парові котлети чи тефтелі з них, варені, тушковані овочі, овочеві пюре, варені яйця, печені яблука, кисломолочні продукти (кефір, ацидофільне молоко, ряжанка), компоти, відвар шипшини"},
                  {'diet_name': 'Дієта № 3',
                   'indications': 'хронічний коліт у період загострення та ремісії зі схильністю до закрепів',
                   'purpose': 'посилення перистальтики тонких та товстих кишок, регулювання процесу випорожнення кишок',
                   'excluded_foods': 'овочі, багаті на ефірні масла (часник, цибуля, редька, бобові), гриби',
                   'restricted_foods': 'макаронні вироби, вироби з тіста, тістечка, жирні сири',
                   'eating_regime': 'дроблене харчування 5—6 разів на день, основну кількість їжі дають у першій половині дня, натще дають кефір. Спеціальної кулінарної обробки їжа не потребує. Слід виключити смажені страви.',
                   'recommended_foods': "овочі багаті на рослинну клітковину (капуста, буряк, морква), житній хліб учорашньої випічки, круп'яні супи на овочевому, м'ясному або рибному бульйоні, нежирне м'ясо чи риба (варені, тушковані, парові), розсипчасті каші (крім пшоняної), велика кількість кисломолочних продуктів, компот із сухофруктів, свіжих фруктів та ягід, печені яблука"},
                  {'diet_name': 'Дієта № 4',
                   'indications': 'гострий ентерит, гострий коліт, хронічний ентероколіт, що загострилися, дизентерія в гострому періоді, що супроводжується проносами',
                   'purpose': 'значне механічне, хімічне та термічне оберігання тонкої та товстої кишок',
                   'excluded_foods': 'свіже молоко, вершки, сметана, сухі фрукти, ягоди, соки з них, овочі, багаті на рослинну клітковину (капуста, буряк, морква, щавель), макаронні вироби',
                   'restricted_foods': 'цукор, варення, вершкове масло',
                   'eating_regime': 'дроблене харчування 5—7 разів на день. Протипоказана холодна їжа, а також надто гаряча',
                   'recommended_foods': "сухарі з білого хліба, супи на знежиреному м'ясному або рибному бульйоні з додаванням слизистих відварів (рисового, вівсяного), слизисті каші (рисова, вівсяна, гречана, манна), парові м'ясні та рибні тефтелі, котлети, варені яйця, киселі"},
                  {'diet_name': 'Дієта № 4 а',
                   'indications': 'хронічний ентероколіт (особливо у поєднанні з хронічним гастритом) у період спаду гострих запальних явищ, дизентерія у період стихання гострих запальних явищ',
                   'purpose': 'значне механічне, хімічне та термічне оберігання тонкої та товстої кишок',
                   'excluded_foods': 'свіже молоко, вершки, сметана, сухі фрукти, ягоди, соки з них, овочі, багаті на рослинну клітковину (капуста, буряк, морква, щавель), макаронні вироби',
                   'restricted_foods': 'цукор, варення, вершкове масло',
                   'eating_regime': 'дроблене харчування 5-7 разів на день. Протипоказана холодна їжа, а також надто гаряча',
                   'recommended_foods': "сухарі з білого хліба, супи на знежиреному м'ясному або рибному бульйоні з додаванням слизистих відварів (рисового, вівсяного), слизисті каші (рисова, вівсяна, гречана, манна), парові м'ясні та рибні тефтелі, котлети, варені яйця, киселі, більше м'ясних та рибних страв, сир, кисломолочні (знежирені) продукти, печені яблука, компот із сухофруктів, не круто зварені яйця"},
                  {'diet_name': 'Дієта № 5',
                   'indications': 'хронічний гепатит з добро­якісним перебігом та прогресуючий вірусний гепатит у пе­ріод одужання хворого, цироз печінки в стадії компенсації, гострий гепатит у період одужання хворого, хронічний холецистит у стадії загострення, жовчнокам\'яна хво­роба.',
                   'purpose': 'сприяння відновленню порушених функцій печінки, стимуляція процесів утворення та виділення жовчі',
                   'excluded_foods': "смажені та жирні страви, що містять у своєму складі важкі для перетравлювання продукти неповного розщеплення жирів (акролеїни та альдегіди), сильні стимулятори секреції шлунка та підшлункової залози (молоко, кава, какао, шоколад, гриби, щавель, шпинат, соки, ягоди, особливо чорна смородина), екстрактивні речовини, прянощі, тугоплавкі жири, продукти, багаті на холестерин та пурини (вим'я, нирки, печінка, щавель, шпинат)",
                   'eating_regime': 'дроблене харчування 5—6 разів на день, останнє приймання їжі не пізніше як за 3 год. до сну (бажано — кефір, ацидофільне молоко з нежирним печивом)',
                   'recommended_foods': "багато солодких продуктів (мед, варення, мармелад, зефір, пастила), білий хліб учорашньої випічки, сухарі з білого хліба, супи круп'яні на овочевому відварі, нежирне варене м'ясо або парові котлети з нього, нежирна варена риба або парові котлети з неї, кисломолочні продукти, сири, напіврідкі каші (гречана, вівсяна), варені овочі, печені яблука; киселі з фруктів та ягід, відвар шипшини, варені яйця"},
                  {'diet_name': 'Дієта № 5 а',
                   'indications': 'гострий холецистит, загострення хронічного холециститу, гострий панкреатит або загострення хронічного панкреатиту, хронічний холецистит у поєднанні з виразковою хворобою шлунка або дванадцятипалої кишки. Дієту рекомендують у перші 5-6 днів після операції на жовчному міхурі.',
                   'purpose': 'Сприяння відновленню порушених функцій печінки та жовчовивідних шляхів, накопичення глікогену у печінці, стимуляція жовчовиділення, обмеження механічного подразнення шлунка та кишок.',
                   'excluded_foods': "смажені та жирні страви, що містять у своєму складі важкі для перетравлювання продукти неповного розщеплення жирів (акролеїни та альдегіди), сильні стимулятори секреції шлунка та підшлункової залози (молоко, кава, какао, шоколад, гриби, щавель, шпинат, соки, ягоди, особливо чорна смородина), екстрактивні речовини, прянощі, тугоплавкі жири, продукти, багаті на холестерин та пурини (вим'я, нирки, печінка, щавель, шпинат)",
                   'eating_regime': 'Дроблене харчування 5-6 разів на день, останнє приймання їжі не пізніше як за 3 год до сну (бажано - кефір, ацидофільне молоко з нежирним печивом).',
                   'recommended_foods': "Багато солодких продуктів (мед, варення, мармелад, зефір, пастила), білий хліб учорашньої випічки, сухарі з білого хліба, супи круп'яні на овочевому відварі, страви більш механічно подрібнені, більша кількість солодких страв, яйця у вигляді омлету або суфле, м'ясо та риба - у вигляді парових тефтелів та суфле, кисломолочні знежирені продукти, печені яблука, киселі з фруктів та ягід, відвар шипшини у великій кількості."},
                  {'diet_name': 'Дієта № 6', 'indications': 'подагра, сечокислий діатез',
                   'purpose': 'сприяння нормалізації пуринового обміну та зниження ендогенного утворення сечової кислоти',
                   'excluded_foods': 'тваринні жири, продукти, багаті на пуринові сполуки (сало, баранина, яловий жир, печінка, нирки, шпроти), міцні бульйони, шпинат, щавель, бобові, шоколад, кава, какао',
                   'restricted_foods': 'кухонна сіль',
                   'eating_regime': 'дроблене харчування 5—6 разів на день, введення 2—2,5 л рідини (під контролем діурезу) — переважно у вигляді чаю, фруктових та ягідних морсів, лужних вод',
                   'recommended_foods': 'продукти, що вміщують лужні радикали (овочі, особливо капуста, морква, буряк, фрукти, ягоди, молоко, рис, гречана, вівсяна каші, картопля, крім смаженої), мед, кавуни, дині, виноград, телятина, варена нежирна яловичина'},
                  {'diet_name': 'Дієта № 7',
                   'indications': 'гострий нефрит у період загострення, хронічний нефрит з незначними змінами в осаду сечі, гіпертонічна хвороба зі змінами у нирках',
                   'purpose': 'оберігання функцій нирок, нормалізуючий вплив на артеріальний тиск та набряки',
                   'eating_regime': 'дроблене харчування 5—7 разів на день. Протипоказані надто холодні та гарячі страви',
                   'excluded_foods': "гострі блюда, м'ясний та рибний бульйони, прянощі, кава, какао, шоколад, бобові, смажене м'ясо, риба",
                   'restricted_foods': 'кухонна сіль до 3—5 г на добу, рідина до 800—1000 мл, вершки, сметана, білки—до 140г',
                   'recommended_foods': 'супи вегетаріанські з овочів та круп, парові котлети з телятини або курятини, овочі варені, вінегрети, каші (гречана, вівсяна, манна), мед, варення, виноград, молоко, молочнокислі продукти, сири'},
                  {'diet_name': 'Дієта № 7 а',
                   'indications': 'гострий нефрит, загострення хронічного нефриту з виявленими змінами в осаді сечі',
                   'purpose': 'оберігання функцій нирок, нормалізуючий вплив на артеріальний тиск та набряки',
                   'eating_regime': 'дроблене харчування 5-7 разів на день. Протипоказані надто холодні та гарячі страви',
                   'excluded_foods': "гострі блюда, м'ясний та рибний бульйони, прянощі, кава, какао, шоколад, бобові, смажене м'ясо, риба, кухонна сіль повністю",
                   'restricted_foods': 'рідина до 800-1000 мл, вершки, сметана, білки - до 50 г на добу',
                   'recommended_foods': 'супи вегетаріанські з овочів та круп, парові котлети з телятини або курятини, овочі варені, вінегрети, каші (гречана, вівсяна, манна), мед, варення, виноград, молоко, молочнокислі продукти, сири. Добова кількість харчових білків значно зменшується до 50 г, збільшується кількість вуглеводів.'},
                  {'diet_name': 'Дієта № 8',
                   'indications': 'ожиріння при відсутності захворювань травного каналу, нирок, серцево-судинної системи',
                   'purpose': 'вплив на обмін речовин для запобігання або виключення надмірного відкладання жиру',
                   'eating_regime': 'часті прийоми малокалорійної їжі у достатньому обсязі, що усуває відчуття голоду. Загальна калорійність зменшується на 20—50 % (залежно від ступеня ожиріння та фізичної активності)',
                   'excluded_foods': "жирні сорти м'яса, макаронні та борошняні вироби, тістечка, інші кондитерські вироби, варення, прянощі, гострі приправи, що збуджують апетит, кава, какао, шоколад",
                   'restricted_foods': 'кухонна сіль до 5—8 г на добу, введення рідини до 1000 мл, вершки, сметана, вершкове масло, картопля, каші (крім гречаної)',
                   'recommended_foods': "вегетаріанські супи, багато варених та тушкованих овочів (кабачки, гарбузи, капуста, буряки, морква), молоко та молочнокислі продукти, знежирені сири, нежирні м'ясо та риба, гречана каша, фрукти та ягоди у сирому вигляді. Заправляти супи та каші слід рослинною олією, замість цукру вживати ксиліт, сорбіт."},
                  {'diet_name': 'Дієта № 9', 'indications': 'цукровий діабет',
                   'purpose': 'створення умов, що підтримують позитивний вуглеводний баланс, запобігання порушенням жирового та білкового обміну у хворого на цукровий діабет',
                   'eating_regime': "приймати їжу слід 5—6 разів на день. Рослинні вуглеводи розподіляти на весь день, на вечерю або на ніч обов'язково слід випити склянку кефіру або ацидофільного молока з метою зменшення бродильних та гнильних процесів у кишках",
                   'excluded_foods': 'варення, солодкий чай, компоти, макаронні та різні кондитерські вироби',
                   'restricted_foods': 'картопля, бобові, солодкі фрукти (кавуни, виноград), кухонна сіль',
                   'recommended_foods': "гречана каша, вегетаріанські супи, варені чи тушковані м'ясо, риба, молоко, кефір, знежирені сири, рослинна олія, варені яйця або омлет"},
                  {'diet_name': 'Дієта № 10',
                   'indications': 'захворювання серцево-судинної системи, ішемічна хвороба серця, природжені та ревматичні вади серця у період компенсації або недостатності кровообігу І ступеня, гіпертонічна хвороба І—II стадії, хронічний гломерулонефрит та пієлонефрит зі змінами в осаду сечі',
                   'purpose': 'створення сприятливих умов для кровообігу, запобігання утворенню набряків або сприяння усуненню вже існуючих набряків, покращання виділення азотистих речовин',
                   'eating_regime': 'приймати їжу 5—6 разів на день, вечеря має бути за 3 год. до сну',
                   'excluded_foods': "жирні м'ясні та рибні страви, бульйони, смажене м'ясо, овочі, тістечка, торти, печінка, нирки, вим'я, сало, гострі страви, прянощі, різні консерви, какао, шоколад, кава",
                   'restricted_foods': 'кухонна сіль, рідина до 800—1000 мл на добу, щавель, шпинат, гриби',
                   'recommended_foods': "супи круп'яні, овочеві, молочні, неміцний бульйон 1 раз на тиждень, парові котлети або тефтелі, варена телятина, курятина, вівсяна та гречана каші, овочеві салати та вінегрет, фрукти, ягоди, соки з них, вживання великої кількості рослинної олії"},
                  {'diet_name': 'Дієта № 10 с',
                   'indications': 'хвороби серця з недостатністю кровообігу II-III ступеня, інфаркт міокарда в гострій та підгострій стадіях, мозковий інсульт',
                   'purpose': 'за допомогою різкого обмеження вживання кухонної солі та збагачення дієти солями калію вплив на порушені функції серця, зменшення набряків, покращання функції нирок. Створення сприятливих умов для кровообігу, запобігання утворенню набряків або сприяння усуненню вже існуючих набряків, покращання виділення азотистих речовин',
                   'eating_regime': 'приймати їжу 5-6 разів на день, вечеря має бути за 3 год до сну',
                   'excluded_foods': "повністю кухонна сіль, жирні м'ясні та рибні страви, бульйони, смажене м'ясо, овочі, тістечка, торти, печінка, нирки, вим'я, сало, гострі страви, прянощі, різні консерви, какао, шоколад, кава",
                   'restricted_foods': 'рідина до 800-1000 мл на добу, щавель, шпинат, гриби',
                   'recommended_foods': "все у протертому вигляді, варене, парене, тушковане. Супи круп'яні, овочеві, молочні, неміцний бульйон 1 раз на тиждень, парові котлети або тефтелі, варена телятина, курятина, вівсяна та гречана каші, овочеві салати та вінегрет, фрукти, ягоди, соки з них, вживання великої кількості рослинної олії"},
                  {'diet_name': 'Дієта № 10 а',
                   'indications': 'атеросклероз судин з переважним ураженням судин серця, мозку, інфаркт міокарда у стадії рубцювання',
                   'purpose': 'запобігання подальшому розвитку атеросклеротичного процесу, при поєднанні атеросклерозу з ожирінням - зниження маси тіла. Створення сприятливих умов для кровообігу, запобігання утворенню набряків або сприяння усуненню вже існуючих набряків, покращання виділення азотистих речовин',
                   'eating_regime': 'приймати їжу 5-6 разів на день, вечеря має бути за 3 год до сну',
                   'excluded_foods': "жирні м'ясні та рибні страви, бульйони, смажене м'ясо, овочі, тістечка, торти, печінка, нирки, вим'я, жирні сорти риби, сало, гострі страви, прянощі, різні консерви, какао, шоколад, кава",
                   'restricted_foods': 'кухонна сіль, рідина до 800-1000 мл на добу, щавель, шпинат, гриби. Особливо обмежуються продукти, багаті на холестерин',
                   'recommended_foods': "продукти, що мають ліпотропну дію, овочі, фрукти, ягоди, соки з них, продукти моря з високим вмістом йоду (морська капуста, трепанги), рослинна олія, вівсяна, гречана каші. Супи круп'яні, овочеві, молочні, неміцний бульйон 1 раз на тиждень, парові котлети або тефтелі, варена телятина, курятина, овочеві салати та вінегрет"},
                  {'diet_name': 'Дієта № 11',
                   'indications': 'туберкульоз у стадії реконвалесценції (в умовах санаторію), виснаження організму після важких захворювань, у тому числі інфекційних, важка анемія, різні нагнійні процеси',
                   'purpose': 'підвищення опірності організму до туберкульозної інфекції, імунної реактивності організму, загальної опірності організму, посилення живлення організму, покращання білкового та вітамінного балансу',
                   'eating_regime': 'приймати їжу 5—6 разів на день з рівномірним (крім вечері) розподілом енергетичної цінності страв',
                   'excluded_foods': 'виключень та обмежень (крім алкоголю, кави) немає',
                   'recommended_foods': "збільшена загальна енергетична цінність їжі до 16736 кДж (4000 ккал). Страви повинні вміщувати велику кількість білків тваринного походження, вітамінів; м'ясо, риба — у будь-якому вигляді, овочі, фрукти, соки, яйця, різноманітні молочні продукти. Для збудження апетиту можна давати прянощі"},
                  {'diet_name': 'Дієта № 12',
                   'indications': 'різні захворювання центральної та периферичної нервової системи',
                   'purpose': 'не подразнювати нервову систему',
                   'recommended_foods': 'морепродукти, нежирні кисломолочні продукти, крупи і макарони, овочі, фрукти, желе, соки, печиво, яйця',
                   'excluded_foods': 'цибуля, часник, шоколад, редька, щавель, чорний чай та кава, какао, алкоголь, гострі соуси та приправи, копченості',
                   'general_characteristics': 'дієта змішана, з обмеженням гострих страв, приправ, а також збуджуючих продуктів'},
                  {'diet_name': 'Дієта № 13',
                   'indications': 'інфекційні важкі захворювання, пневмонія в гострий гарячковий період, ангіна, гострий сепсис, післяопераційний стан',
                   'purpose': 'підтримання загального стану організму шляхом посиленого його живлення в гарячковий або післяопераційний період',
                   'eating_regime': 'дроблене харчування 6—8 разів на день, їжа може бути гарячою або теплою, при гіперпірексії — охолодженою. Якщо хворий знаходиться у важкому стані, вдень багато спить, то його годують, коли він прокидається, і навіть уночі',
                   'excluded_foods': "смажені, гострі страви, жирні м'ясо, риба, сало, кава, алкогольні напої",
                   'restricted_foods': 'кухонна сіль до 8 г. на добу, овочі, що вміщують багато клітковини (капуста, буряки, редька)',
                   'recommended_foods': "хворому дають багато рідини (до 2 л у вигляді соків, відвару шипшини, компотів). Страви мають бути рідкими або напіврідкими, неміцні рибні та м'ясні бульйони, хліб білий учорашньої випічки, білі сухарі, суп-пюре з каш на овочевому бульйоні, слизисті каші, не круто зварені яйця, молоко, вершки, сметана, кисломолочні продукти"},
                  {'diet_name': 'Дієта № 14',
                   'indications': "фосфатурія з лужною реакцією сечі та випаданням осаду фосфорно-калієвих солей, сечокам'яна хвороба з фосфатними каменями",
                   'purpose': 'сприяти відновленню кислої реакції сечі, таким чином попереджаючи випадання осаду фосфатів',
                   'eating_regime': 'приймають їжу 4—5 разів на день. Дають багато рідини—до 1,5—2 л. Кулінарна обробка їжі звичайна',
                   'restricted_foods': "масло, м'ясні та рибні супи",
                   'excluded_foods': 'молоко, сир, кава, какао, шоколад, бобові, міцні бульйони, продукти, щавель, шпинат, петрушка, агрус, прянощі, алкогольні напої',
                   'recommended_foods': "фрукти, ягоди, соки з них, нежирні м'ясо, риба, гречана, вівсяна, рисова каші, мед, варення, мармелад"},
                  {'diet_name': 'Дієта № 15',
                   'indications': 'різні захворювання у період одужання при відсутності показань до призначення спеціальної лікувальної дієти та при нормальному стані органів травлення',
                   'purpose': 'в умовах лікувального закладу забезпечити харчування хворого за фізіологічними нормами',
                   'eating_regime': 'приймають їжу 4—5 разів на день',
                   'excluded_foods': "жирне м'ясо (свинина, баранина), сало, тістечка, свіжий хліб",
                   'restricted_foods': 'гострі страви, прянощі, кава, какао, шоколад',
                   'recommended_foods': "нежирне м'ясо, риба у будь-якій кулінарній обробці, різні молочні продукти, овочі, картопля у вигляді різних страв та гарнірів, частина овочів у сирому вигляді (салати), фрукти, ягоди, соки та компоти з них"},
                  {'diet_name': 'Дієта № 0',
                   'indications': '3-5 доба після операцій на шлунково-кишковому тракті, захворювання центральної нервової системи з порушенням свідомості (порушення мозкового кровообігу, черепно-мозкова травма)',
                   'purpose': 'рідка малокалорійна дієта з обмеженням солі, включає легкозасвоювані продукти',
                   'eating_regime': 'режим харчування- кожні 2 години на протязі дня і ночі',
                   'recommended_foods': 'слизисті круп’яні відвари, легкий, м’ясний бульйон, фруктове желе, відвар шипшини, негазована мінеральна вода',
                   'restricted_foods': 'кухонна сіль'}]
diet_data_list_en = [{'diet_name': 'Diet № 1',
                      'indications': 'acute diseases of the upper parts of the alimentary canal, which last for 1-3 months, or chronic diseases that have worsened (esophagitis), gastritis with increased or normal acidity, duodenitis, peptic ulcer disease of the stomach and duodenum in the phase of moderate exacerbation.',
                      'purpose': 'Promoting the healing of stomach and duodenal ulcers, elimination of inflammatory processes in the upper parts of the alimentary canal.',
                      'excluded_foods': 'foods that remain in the stomach for a long time and irritate it (animal fats, vegetable fiber), stimulants of gastric secretion, spicy foods, spices, strong broths, mushrooms, legumes, coffee, chocolate, cocoa.',
                      'restricted_foods': 'table salt, lactic acid products.',
                      'eating_regime': 'The diet involves eating 6-7 times a day every 2-3 hours. ',
                      'recommended_foods': 'slimy soups from cereals (oat, buckwheat, rice, semolina), milk, cream, fresh low-fat sour cream, beef, veal, steamed fish cutlets, meatballs, mashed porridge, boiled eggs, pickled berries and fruits, diluted juices from them, bread '},
                     {'diet_name': 'Diet № 1 a',
                      'indications': 'exacerbation of peptic ulcer disease of the stomach and duodenum (first 3-7 days), exacerbation of gastritis with excessive acidity, burn of the esophagus or stomach',
                      'purpose': 'Facilitating the healing of stomach and duodenal ulcers, elimination of inflammatory processes in the upper parts of the digestive tract during an exacerbation',
                      'excluded_foods': 'foods that linger in the stomach for a long time and irritate it (animal fats, vegetable fiber), gastric secretion stimulants, spicy foods, spices, strong broths, mushrooms, legumes, coffee, chocolate, cocoa',
                      'restricted_foods': 'table salt, lactic acid products',
                      'eating_regime': 'The diet involves eating 6-7 times a day every 2-3 hours in small portions. ',
                      'general_characteristics': 'Dishes should be liquid or semi-liquid with reduced calorie content. ',
                      'recommended_foods': 'slimy soups from cereals (oat, buckwheat, rice, semolina), milk, cream, fresh low-fat sour cream, beef, veal, steamed fish cutlets, meatballs, mashed porridge, hard-boiled eggs, pickled berries and fruits, diluted juices from them '},
                     {'diet_name': 'Diet № 1 b',
                      'indications': 'exacerbation of peptic ulcer disease of the stomach and duodenum (first 10-20 days), exacerbation of chronic gastritis (first 7-10 days)',
                      'purpose': 'Facilitating the healing of stomach and duodenal ulcers, elimination of inflammatory processes in the upper parts of the digestive tract during an exacerbation',
                      'excluded_foods': 'foods that linger in the stomach for a long time and irritate it (animal fats, vegetable fiber), gastric secretion stimulants, spicy foods, spices, strong broths, mushrooms, legumes, coffee, chocolate, cocoa',
                      'restricted_foods': 'table salt, lactic acid products',
                      'eating_regime': 'The diet involves eating 6-7 times a day every 2-3 hours in small portions. ',
                      'recommended_foods': 'slimy soups from cereals (oat, buckwheat, rice, semolina), milk, cream, fresh low-fat sour cream, beef, veal, steamed fish cutlets, meatballs, mashed porridge, boiled eggs, pickled berries and fruits, diluted juices from them, bread '},
                     {'diet_name': 'Diet № 2',
                      'indications': 'acute gastritis with reduced acidity, chronic gastritis with reduced acidity in the exacerbation phase, the period of convalescence after enteritis, colitis',
                      'purpose': 'increasing gastric secretion, increasing the secretory activity of other digestive glands, improving the motor function of the stomach and intestines',
                      'excluded_foods': 'legumes, mushrooms, fatty meats (goose, duck, pork, lamb), fried dishes',
                      'restricted_foods': 'fresh milk, cream, sour cream, animal fat',
                      'eating_regime': 'crushed food 5-6 times a day',
                      'recommended_foods': "yesterday's baked white bread, cereal soups (except millet) on low-fat meat or fish broth, boiled meat (beef, veal, chicken) and low-fat fish or steam cutlets or meatballs from them, boiled, stewed vegetables, "},
                     {'diet_name': 'Diet № 3',
                      'indications': 'chronic colitis in the period of exacerbation and remission with a tendency to constipation',
                      'purpose': 'strengthening of peristalsis of small and large intestines, regulation of bowel emptying process',
                      'excluded_foods': 'vegetables rich in essential oils (garlic, onion, radish, legumes), mushrooms',
                      'restricted_foods': 'pasta, dough products, cakes, fatty cheeses',
                      'eating_regime': 'crushed food 5-6 times a day, the main amount of food is given in the first half of the day, kefir is given on an empty stomach. ',
                      'recommended_foods': 'vegetables rich in vegetable fiber (cabbage, beets, carrots), rye bread made yesterday, cereal soups in vegetable, meat or fish broth, lean meat or fish (boiled, stewed, steamed), loose cereals (except '},
                     {'diet_name': 'Diet № 4',
                      'indications': 'acute enteritis, acute colitis, chronic enterocolitis, aggravated, dysentery in the acute period, accompanied by diarrhea',
                      'purpose': 'significant mechanical, chemical and thermal protection of the small and large intestines',
                      'excluded_foods': 'fresh milk, cream, sour cream, dried fruits, berries, juices from them, vegetables rich in vegetable fiber (cabbage, beets, carrots, sorrel), pasta',
                      'restricted_foods': 'sugar, jam, butter',
                      'eating_regime': 'crushed food 5-7 times a day. ',
                      'recommended_foods': 'crackers from white bread, soups on low-fat meat or fish broth with the addition of slimy broths (rice, oatmeal), slimy porridges (rice, oatmeal, buckwheat, semolina), steamed meat and fish meatballs, cutlets, boiled eggs, jelly'},
                     {'diet_name': 'Diet № 4 a',
                      'indications': 'chronic enterocolitis (especially in combination with chronic gastritis) in the period of decline of acute inflammatory phenomena, dysentery in the period of subsidence of acute inflammatory phenomena',
                      'purpose': 'significant mechanical, chemical and thermal protection of the small and large intestines',
                      'excluded_foods': 'fresh milk, cream, sour cream, dried fruits, berries, juices from them, vegetables rich in vegetable fiber (cabbage, beets, carrots, sorrel), pasta',
                      'restricted_foods': 'sugar, jam, butter',
                      'eating_regime': 'crushed food 5-7 times a day. ',
                      'recommended_foods': 'crackers from white bread, soups on low-fat meat or fish broth with the addition of slimy broths (rice, oatmeal), slimy porridges (rice, oatmeal, buckwheat, semolina), steamed meat and fish meatballs, cutlets, boiled eggs, jelly '},
                     {'diet_name': 'Diet № 5',
                      'indications': "chronic hepatitis with a benign course and progressive viral hepatitis during the patient's recovery, liver cirrhosis in the compensation stage, acute hepatitis during the patient's recovery, chronic cholecystitis in the exacerbation stage, gallstone disease.",
                      'purpose': 'promoting the restoration of impaired liver functions, stimulating the processes of formation and secretion of bile',
                      'excluded_foods': 'fried and fatty dishes containing difficult-to-digest products of incomplete fat breakdown (acrolein and aldehydes), strong stimulators of gastric and pancreatic secretion (milk, coffee, cocoa, chocolate, mushrooms, sorrel, spinach, juices, berries, especially ',
                      'eating_regime': 'crushed food 5-6 times a day, the last meal no later than 3 hours. ',
                      'recommended_foods': 'a lot of sweet products (honey, jam, marmalade, marshmallows, pastila), white bread made yesterday, white bread crackers, vegetable soups, low-fat boiled meat or steam cutlets from it, low-fat boiled fish or steam cutlets '},
                     {'diet_name': 'Diet № 5 a',
                      'indications': 'acute cholecystitis, exacerbation of chronic cholecystitis, acute pancreatitis or exacerbation of chronic pancreatitis, chronic cholecystitis in combination with peptic ulcer disease of the stomach or duodenum. ',
                      'purpose': 'Helping to restore impaired functions of the liver and biliary tract, accumulation of glycogen in the liver, stimulation of bile secretion, limitation of mechanical irritation of the stomach and intestines.',
                      'excluded_foods': 'fried and fatty dishes containing difficult-to-digest products of incomplete fat breakdown (acrolein and aldehydes), strong stimulators of gastric and pancreatic secretion (milk, coffee, cocoa, chocolate, mushrooms, sorrel, spinach, juices, berries, especially ',
                      'eating_regime': 'Crushed food 5-6 times a day, the last meal no later than 3 hours before bedtime (preferably - kefir, acidophilic milk with low-fat cookies).',
                      'recommended_foods': "A lot of sweet products (honey, jam, marmalade, marshmallows, pastila), white bread from yesterday's baking, white bread crackers, cereal soups on vegetable broth, dishes that are more mechanically chopped, a larger number of sweet dishes, eggs in the form of an omelet or souffle, "},
                     {'diet_name': 'Diet № 6',
                      'indications': 'gout, uric acid diathesis',
                      'purpose': 'promoting the normalization of purine metabolism and reducing the endogenous formation of uric acid',
                      'excluded_foods': 'animal fats, foods rich in purine compounds (lard, lamb, lard, liver, kidneys, sprats), strong broths, spinach, sorrel, legumes, chocolate, coffee, cocoa',
                      'restricted_foods': 'table salt',
                      'eating_regime': 'crushed food 5-6 times a day, administration of 2-2.5 liters of liquid (under diuresis control) - mainly in the form of tea, fruit and berry juices, alkaline water',
                      'recommended_foods': 'foods containing alkaline radicals (vegetables, especially cabbage, carrots, beets, fruits, berries, milk, rice, buckwheat, oatmeal, potatoes, except fried), honey, watermelons, melons, grapes, veal, boiled lean beef'},
                     {'diet_name': 'Diet № 7',
                      'indications': 'acute nephritis in the period of exacerbation, chronic nephritis with minor changes in the urine sediment, hypertensive disease with changes in the kidneys',
                      'purpose': 'protection of kidney functions, normalizing effect on blood pressure and edema',
                      'eating_regime': 'crushed food 5-7 times a day. ',
                      'excluded_foods': 'spicy dishes, meat and fish broths, spices, coffee, cocoa, chocolate, legumes, fried meat, fish',
                      'restricted_foods': 'table salt up to 3-5 g per day, liquid up to 800-1000 ml, cream, sour cream, proteins - up to 140 g',
                      'recommended_foods': 'vegetarian soups from vegetables and cereals, steam cutlets from veal or chicken, boiled vegetables, vinaigrettes, cereals (buckwheat, oat, semolina), honey, jam, grapes, milk, lactic acid products, cheeses'},
                     {'diet_name': 'Diet № 7 a',
                      'indications': 'acute nephritis, exacerbation of chronic nephritis with detected changes in urine sediment',
                      'purpose': 'protection of kidney functions, normalizing effect on blood pressure and edema',
                      'eating_regime': 'crushed food 5-7 times a day. ',
                      'excluded_foods': 'spicy dishes, meat and fish broths, spices, coffee, cocoa, chocolate, legumes, fried meat, fish, table salt completely',
                      'restricted_foods': 'liquid up to 800-1000 ml, cream, sour cream, proteins - up to 50 g per day',
                      'recommended_foods': 'vegetarian soups from vegetables and cereals, steam cutlets from veal or chicken, boiled vegetables, vinaigrettes, cereals (buckwheat, oat, semolina), honey, jam, grapes, milk, lactic acid products, cheeses. '},
                     {'diet_name': 'Diet № 8',
                      'indications': 'obesity in the absence of diseases of the digestive tract, kidneys, cardiovascular system',
                      'purpose': 'impact on metabolism to prevent or eliminate excessive fat deposition',
                      'eating_regime': 'frequent meals of low-calorie food in a sufficient amount, which eliminates the feeling of hunger. ',
                      'excluded_foods': 'fatty meats, pasta and flour products, cakes, other confectionery, jams, spices, spicy seasonings that stimulate the appetite, coffee, cocoa, chocolate',
                      'restricted_foods': 'table salt up to 5-8 g per day, fluid intake up to 1000 ml, cream, sour cream, butter, potatoes, porridge (except buckwheat)',
                      'recommended_foods': 'vegetarian soups, a lot of boiled and stewed vegetables (zucchini, pumpkins, cabbage, beets, carrots), milk and lactic acid products, low-fat cheeses, low-fat meat and fish, buckwheat porridge, fruits and berries in raw form. '},
                     {'diet_name': 'Diet № 9',
                      'indications': 'diabetes',
                      'purpose': 'creation of conditions that support a positive carbohydrate balance, prevention of disturbances in fat and protein metabolism in patients with diabetes',
                      'eating_regime': 'you should eat 5-6 times a day. ',
                      'excluded_foods': 'jam, sweet tea, compotes, macaroni and various confectionery products',
                      'restricted_foods': 'potatoes, legumes, sweet fruits (watermelons, grapes), table salt',
                      'recommended_foods': 'buckwheat porridge, vegetarian soups, boiled or stewed meat, fish, milk, kefir, low-fat cheeses, vegetable oil, boiled eggs or omelet'},
                     {'diet_name': 'Diet № 10',
                      'indications': 'diseases of the cardiovascular system, ischemic heart disease, congenital and rheumatic heart defects in the period of compensation or circulatory insufficiency of the first degree, hypertensive disease of the first and second stages, chronic glomerulonephritis and pyelonephritis with changes in the urine sediment',
                      'purpose': 'creating favorable conditions for blood circulation, preventing the formation of edema or promoting the elimination of already existing edema, improving the release of nitrogenous substances',
                      'eating_regime': 'eat 5-6 times a day, dinner should be in 3 hours. ',
                      'excluded_foods': 'fatty meat and fish dishes, broths, fried meat, vegetables, cakes, cakes, liver, kidneys, udder, lard, spicy dishes, spices, various preserves, cocoa, chocolate, coffee',
                      'restricted_foods': 'table salt, liquid up to 800-1000 ml per day, sorrel, spinach, mushrooms',
                      'recommended_foods': 'cereal, vegetable, milk soups, weak broth once a week, steam cutlets or meatballs, boiled veal, chicken, oatmeal and buckwheat porridge, vegetable salads and vinaigrette, fruits, berries, their juices, consumption of large amounts of vegetable oil'},
                     {'diet_name': 'Diet № 10 c',
                      'indications': 'heart disease with circulatory insufficiency of the II-III degree, myocardial infarction in the acute and subacute stages, cerebral stroke',
                      'purpose': 'by sharply limiting the use of table salt and enriching the diet with potassium salts, the effect on impaired heart functions, reduction of edema, improvement of kidney function. ',
                      'eating_regime': 'eat 5-6 times a day, dinner should be 3 hours before bedtime',
                      'excluded_foods': 'all table salt, fatty meat and fish dishes, broths, fried meat, vegetables, cakes, cakes, liver, kidneys, udder, lard, spicy dishes, spices, various preserves, cocoa, chocolate, coffee',
                      'restricted_foods': 'liquid up to 800-1000 ml per day, sorrel, spinach, mushrooms',
                      'recommended_foods': 'everything in pureed form, boiled, steamed, stewed. '},
                     {'diet_name': 'Дієта № 10 a',
                      'indications': 'atherosclerosis of vessels with predominant damage to vessels of the heart, brain, myocardial infarction in the stage of scarring',
                      'purpose': 'prevention of the further development of the atherosclerotic process, when atherosclerosis is combined with obesity - a decrease in body weight. ',
                      'eating_regime': 'eat 5-6 times a day, dinner should be 3 hours before bedtime',
                      'excluded_foods': 'fatty meat and fish dishes, broths, fried meat, vegetables, cakes, cakes, liver, kidneys, udder, fatty fish, lard, spicy dishes, spices, various preserves, cocoa, chocolate, coffee',
                      'restricted_foods': 'table salt, liquid up to 800-1000 ml per day, sorrel, spinach, mushrooms. ',
                      'recommended_foods': 'foods that have a lipotropic effect, vegetables, fruits, berries, juices from them, seafood with a high content of iodine (sea kale, trepang), vegetable oil, oatmeal, buckwheat porridge. '},
                     {'diet_name': 'Diet № 11',
                      'indications': 'tuberculosis in the stage of convalescence (in sanatorium conditions), exhaustion of the body after serious diseases, including infectious ones, severe anemia, various purulent processes',
                      'purpose': "increasing the body's resistance to tuberculosis infection, the body's immune reactivity, the body's general resistance, strengthening the body's nutrition, improving the protein and vitamin balance",
                      'eating_regime': 'to eat 5-6 times a day with an even (except for dinner) distribution of the energy value of dishes',
                      'excluded_foods': 'there are no exceptions and restrictions (except for alcohol, coffee).',
                      'recommended_foods': 'increased total energy value of food to 16736 kJ (4000 kcal). '},
                     {'diet_name': 'Diet № 12',
                      'indications': 'various diseases of the central and peripheral nervous system',
                      'purpose': 'do not irritate the nervous system',
                      'recommended_foods': 'seafood, low-fat dairy products, cereals and pasta, vegetables, fruits, jelly, juices, cookies, eggs',
                      'excluded_foods': 'onion, garlic, chocolate, radish, sorrel, black tea and coffee, cocoa, alcohol, spicy sauces and seasonings, smoked meats',
                      'general_characteristics': 'the diet is mixed, with the restriction of spicy dishes, seasonings, as well as exciting products'},
                     {'diet_name': 'Дієта № 13',
                      'indications': 'severe infectious diseases, pneumonia in the acute febrile period, angina, acute sepsis, postoperative condition',
                      'purpose': 'maintenance of the general state of the body by means of enhanced nutrition during the febrile or postoperative period',
                      'eating_regime': 'crushed food 6-8 times a day, food can be hot or warm, in case of hyperpyrexia - cooled. ',
                      'excluded_foods': 'fried, spicy dishes, fatty meat, fish, lard, coffee, alcoholic beverages',
                      'restricted_foods': 'table salt up to 8 g per day, vegetables containing a lot of fiber (cabbage, beets, radishes)',
                      'recommended_foods': 'the patient is given a lot of liquid (up to 2 liters in the form of juices, rosehip decoction, compotes). '},
                     {'diet_name': 'Diet № 14',
                      'indications': 'phosphaturia with an alkaline reaction of urine and precipitation of phosphorus-potassium salts, urolithiasis with phosphate stones',
                      'purpose': 'contribute to the recovery of the acidic reaction of urine, thus preventing the precipitation of phosphate deposits',
                      'eating_regime': 'take food 4-5 times a day. ',
                      'restricted_foods': 'butter, meat and fish soups',
                      'excluded_foods': 'milk, cheese, coffee, cocoa, chocolate, legumes, strong broths, foods, sorrel, spinach, parsley, gooseberries, spices, alcoholic beverages',
                      'recommended_foods': 'fruits, berries, their juices, lean meat, fish, buckwheat, oatmeal, rice porridge, honey, jam, marmalade'},
                     {'diet_name': 'Diet № 15',
                      'indications': 'various diseases during the recovery period in the absence of indications for the appointment of a special therapeutic diet and in the normal state of the digestive organs',
                      'purpose': "in the conditions of a medical institution, ensure the patient's nutrition according to physiological norms",
                      'eating_regime': 'take food 4-5 times a day',
                      'excluded_foods': 'fatty meat (pork, lamb), lard, cakes, fresh bread',
                      'restricted_foods': 'spicy dishes, spices, coffee, cocoa, chocolate',
                      'recommended_foods': 'lean meat, fish in any culinary processing, various dairy products, vegetables, potatoes in the form of various dishes and side dishes, part of vegetables in raw form (salads), fruits, berries, juices and compotes from them'},
                     {'diet_name': 'Diet № 0',
                      'indications': '3-5 days after operations on the gastrointestinal tract, diseases of the central nervous system with impaired consciousness (impaired cerebral blood circulation, traumatic brain injury)',
                      'purpose': 'liquid low-calorie diet with salt restriction, includes easily digestible products',
                      'eating_regime': 'feeding regime - every 2 hours during the day and night',
                      'recommended_foods': 'slimy cereal broths, light, meat broth, fruit jelly, rosehip broth, non-carbonated mineral water',
                      'restricted_foods': 'table salt'}]
diet_data = {
    "Дієта № 1": {
        "indications": "гострі захворювання верхніх відділів травного каналу, які тривають протягом 1— 3 міс., або хронічні захворювання, що загострилися (езофагіт), гастрит з підвищеною або нормальною кислотністю, дуоденіт, виразкова хвороба шлунка та дванадцятипалої кишки у фазі помірного загострення.",
        "purpose": "Сприяння загоюванню виразок шлунка та дванадцятипалої кишки, ліквідації запальних процесів у верхніх відділах травного каналу.",
        "excluded_foods": "страви, що довго затримуються в шлунку та подразнюють його (тваринні жири, рослинна клітковина), стимулятори шлункової секреції, гострі страви, прянощі, міцні бульйони, гриби, бобові, кава, шоколад, какао.",
        "restricted_foods": "кухонна сіль, молочнокислі продукти.",
        "eating_regime": "Дієта передбачає харчування 6- 7 разів на день через кожні 2-3 год. невеликими порціями. Більша кількість їжі припадає на 1-й, 2-й сніданок та обід. Страви повинні бути механічно подрібненими, вареними, протертими, пареними.",
        "recommended_foods": "слизисті супи з круп (вівсяної, гречаної, рисової, манної), молоко, вершки, свіжа нежирна сметана, яловичі, телячі, рибні парові котлети, тефтелі, протерті каші, варені яйця, киселі з ягід та фруктів, розведені соки з них, хліб білий учорашньої випічки."
    },
    "Дієта № 1 а": {
        "indications": "загострення виразкової хвороби шлунка та дванадцятипалої кишки (перші 3-7 днів), загострення гастриту з надмірною кислотністю, опік стравоходу чи шлунка",
        "purpose": "Сприяння загоюванню виразок шлунка та дванадцятипалої кишки, ліквідації запальних процесів у верхніх відділах травного каналу під час загострення",
        "excluded_foods": "страви, що довго затримуються в шлунку та подразнюють його (тваринні жири, рослинна клітковина), стимулятори шлункової секреції, гострі страви, прянощі, міцні бульйони, гриби, бобові, кава, шоколад, какао",
        "restricted_foods": "кухонна сіль, молочнокислі продукти",
        "eating_regime": "Дієта передбачає харчування 6-7 разів на день через кожні 2-3 год невеликими порціями. Більша кількість їжі припадає на 1-й, 2-й сніданок та обід",
        "general_characteristics": "Страви повинні бути рідкими або напіврідкими зі зменшеною калорійністю. Хворим дають багато вершків, молока, не круто зварені яйця (щоденно), молочні киселі",
        "recommended_foods": "слизисті супи з круп (вівсяної, гречаної, рисової, манної), молоко, вершки, свіжа нежирна сметана, яловичі, телячі, рибні парові котлети, тефтелі, протерті каші, варені яйця не круто, киселі з ягід та фруктів, розведені соки з них, хліб білий учорашньої випічки"
    },
    "Дієта № 1 б": {
        "indications": "загострення виразкової хвороби шлунка та дванадцятипалої кишки (перші 10-20 днів), загострення хронічного гастриту (перші 7-10 днів)",
        "purpose": "Сприяння загоюванню виразок шлунка та дванадцятипалої кишки, ліквідації запальних процесів у верхніх відділах травного каналу під час загострення",
        "excluded_foods": "страви, що довго затримуються в шлунку та подразнюють його (тваринні жири, рослинна клітковина), стимулятори шлункової секреції, гострі страви, прянощі, міцні бульйони, гриби, бобові, кава, шоколад, какао",
        "restricted_foods": "кухонна сіль, молочнокислі продукти",
        "eating_regime": "Дієта передбачає харчування 6-7 разів на день через кожні 2-3 год невеликими порціями. Більша кількість їжі припадає на 1-й, 2-й сніданок та обід",
        "recommended_foods": "слизисті супи з круп (вівсяної, гречаної, рисової, манної), молоко, вершки, свіжа нежирна сметана, яловичі, телячі, рибні парові котлети, тефтелі, протерті каші, варені яйця, киселі з ягід та фруктів, розведені соки з них, хліб білий учорашньої випічки, сухарі з білого хліба, протертий нежирний сир, парові тефтелі з телятини, фруктові киселі"
    },
    "Дієта № 2": {
        "indications": "гострий гастрит зі зниженою кислотністю, хронічний гастрит зі зниженою кислотністю у фазі загострення, період реконвалесценції після ентериту, коліту",
        "purpose": "підвищення секреції шлунка, підвищення секреторної активності інших травних залоз, покращення моторної функції шлунка та кишок",
        "excluded_foods": "бобові, гриби, жирні сорти м'яса (гусятина, качатина, свинина, баранина), смажені страви",
        "restricted_foods": "свіже молоко, вершки, сметана, тваринний жир",
        "eating_regime": "дроблене харчування 5-6 разів на день",
        "recommended_foods": "хліб білий учорашньої випічки, супи круп'яні (крім пшона) на знежиреному м'ясному або рибному бульйоні, відварні м'ясо (яловичина, телятина, курятина) та риба нежирних сортів або парові котлети чи тефтелі з них, варені, тушковані овочі, овочеві пюре, варені яйця, печені яблука, кисломолочні продукти (кефір, ацидофільне молоко, ряжанка), компоти, відвар шипшини"
    },
    "Дієта № 3": {
        "indications": "хронічний коліт у період загострення та ремісії зі схильністю до закрепів",
        "purpose": "посилення перистальтики тонких та товстих кишок, регулювання процесу випорожнення кишок",
        "excluded_foods": "овочі, багаті на ефірні масла (часник, цибуля, редька, бобові), гриби",
        "restricted_foods": "макаронні вироби, вироби з тіста, тістечка, жирні сири",
        "eating_regime": "дроблене харчування 5—6 разів на день, основну кількість їжі дають у першій половині дня, натще дають кефір. Спеціальної кулінарної обробки їжа не потребує. Слід виключити смажені страви.",
        "recommended_foods": "овочі багаті на рослинну клітковину (капуста, буряк, морква), житній хліб учорашньої випічки, круп'яні супи на овочевому, м'ясному або рибному бульйоні, нежирне м'ясо чи риба (варені, тушковані, парові), розсипчасті каші (крім пшоняної), велика кількість кисломолочних продуктів, компот із сухофруктів, свіжих фруктів та ягід, печені яблука"
    },
    "Дієта № 4": {
        "indications": "гострий ентерит, гострий коліт, хронічний ентероколіт, що загострилися, дизентерія в гострому періоді, що супроводжується проносами",
        "purpose": "значне механічне, хімічне та термічне оберігання тонкої та товстої кишок",
        "excluded_foods": "свіже молоко, вершки, сметана, сухі фрукти, ягоди, соки з них, овочі, багаті на рослинну клітковину (капуста, буряк, морква, щавель), макаронні вироби",
        "restricted_foods": "цукор, варення, вершкове масло",
        "eating_regime": "дроблене харчування 5—7 разів на день. Протипоказана холодна їжа, а також надто гаряча",
        "recommended_foods": "сухарі з білого хліба, супи на знежиреному м'ясному або рибному бульйоні з додаванням слизистих відварів (рисового, вівсяного), слизисті каші (рисова, вівсяна, гречана, манна), парові м'ясні та рибні тефтелі, котлети, варені яйця, киселі"
    },
    "Дієта № 4 а": {
        "indications": "хронічний ентероколіт (особливо у поєднанні з хронічним гастритом) у період спаду гострих запальних явищ, дизентерія у період стихання гострих запальних явищ",
        "purpose": "значне механічне, хімічне та термічне оберігання тонкої та товстої кишок",
        "excluded_foods": "свіже молоко, вершки, сметана, сухі фрукти, ягоди, соки з них, овочі, багаті на рослинну клітковину (капуста, буряк, морква, щавель), макаронні вироби",
        "restricted_foods": "цукор, варення, вершкове масло",
        "eating_regime": "дроблене харчування 5-7 разів на день. Протипоказана холодна їжа, а також надто гаряча",
        "recommended_foods": "сухарі з білого хліба, супи на знежиреному м'ясному або рибному бульйоні з додаванням слизистих відварів (рисового, вівсяного), слизисті каші (рисова, вівсяна, гречана, манна), парові м'ясні та рибні тефтелі, котлети, варені яйця, киселі, більше м'ясних та рибних страв, сир, кисломолочні (знежирені) продукти, печені яблука, компот із сухофруктів, не круто зварені яйця"
    },
    "Дієта № 5": {
        "indications": "хронічний гепатит з добро­якісним перебігом та прогресуючий вірусний гепатит у пе­ріод одужання хворого, цироз печінки в стадії компенсації, гострий гепатит у період одужання хворого, хронічний холецистит у стадії загострення, жовчнокам'яна хво­роба.",
        "purpose": "сприяння відновленню порушених функцій печінки, стимуляція процесів утворення та виділення жовчі",
        "excluded_foods": "смажені та жирні страви, що містять у своєму складі важкі для перетравлювання продукти неповного розщеплення жирів (акролеїни та альдегіди), сильні стимулятори секреції шлунка та підшлункової залози (молоко, кава, какао, шоколад, гриби, щавель, шпинат, соки, ягоди, особливо чорна смородина), екстрактивні речовини, прянощі, тугоплавкі жири, продукти, багаті на холестерин та пурини (вим'я, нирки, печінка, щавель, шпинат)",
        "eating_regime": "дроблене харчування 5—6 разів на день, останнє приймання їжі не пізніше як за 3 год. до сну (бажано — кефір, ацидофільне молоко з нежирним печивом)",
        "recommended_foods": "багато солодких продуктів (мед, варення, мармелад, зефір, пастила), білий хліб учорашньої випічки, сухарі з білого хліба, супи круп'яні на овочевому відварі, нежирне варене м'ясо або парові котлети з нього, нежирна варена риба або парові котлети з неї, кисломолочні продукти, сири, напіврідкі каші (гречана, вівсяна), варені овочі, печені яблука; киселі з фруктів та ягід, відвар шипшини, варені яйця"
    },
    "Дієта № 5 а": {
        "indications": "гострий холецистит, загострення хронічного холециститу, гострий панкреатит або загострення хронічного панкреатиту, хронічний холецистит у поєднанні з виразковою хворобою шлунка або дванадцятипалої кишки. Дієту рекомендують у перші 5-6 днів після операції на жовчному міхурі.",
        "purpose": "Сприяння відновленню порушених функцій печінки та жовчовивідних шляхів, накопичення глікогену у печінці, стимуляція жовчовиділення, обмеження механічного подразнення шлунка та кишок.",
        "excluded_foods": "смажені та жирні страви, що містять у своєму складі важкі для перетравлювання продукти неповного розщеплення жирів (акролеїни та альдегіди), сильні стимулятори секреції шлунка та підшлункової залози (молоко, кава, какао, шоколад, гриби, щавель, шпинат, соки, ягоди, особливо чорна смородина), екстрактивні речовини, прянощі, тугоплавкі жири, продукти, багаті на холестерин та пурини (вим'я, нирки, печінка, щавель, шпинат)",
        "eating_regime": "Дроблене харчування 5-6 разів на день, останнє приймання їжі не пізніше як за 3 год до сну (бажано - кефір, ацидофільне молоко з нежирним печивом).",
        "recommended_foods": "Багато солодких продуктів (мед, варення, мармелад, зефір, пастила), білий хліб учорашньої випічки, сухарі з білого хліба, супи круп'яні на овочевому відварі, страви більш механічно подрібнені, більша кількість солодких страв, яйця у вигляді омлету або суфле, м'ясо та риба - у вигляді парових тефтелів та суфле, кисломолочні знежирені продукти, печені яблука, киселі з фруктів та ягід, відвар шипшини у великій кількості."
    },
    "Дієта № 6": {
        "indications": "подагра, сечокислий діатез",
        "purpose": "сприяння нормалізації пуринового обміну та зниження ендогенного утворення сечової кислоти",
        "excluded_foods": "тваринні жири, продукти, багаті на пуринові сполуки (сало, баранина, яловий жир, печінка, нирки, шпроти), міцні бульйони, шпинат, щавель, бобові, шоколад, кава, какао",
        "restricted_foods": "кухонна сіль",
        "eating_regime": "дроблене харчування 5—6 разів на день, введення 2—2,5 л рідини (під контролем діурезу) — переважно у вигляді чаю, фруктових та ягідних морсів, лужних вод",
        "recommended_foods": "продукти, що вміщують лужні радикали (овочі, особливо капуста, морква, буряк, фрукти, ягоди, молоко, рис, гречана, вівсяна каші, картопля, крім смаженої), мед, кавуни, дині, виноград, телятина, варена нежирна яловичина"
    },
    "Дієта № 7": {
        "indications": "гострий нефрит у період загострення, хронічний нефрит з незначними змінами в осаду сечі, гіпертонічна хвороба зі змінами у нирках",
        "purpose": "оберігання функцій нирок, нормалізуючий вплив на артеріальний тиск та набряки",
        "eating_regime": "дроблене харчування 5—7 разів на день. Протипоказані надто холодні та гарячі страви",
        "excluded_foods": "гострі блюда, м'ясний та рибний бульйони, прянощі, кава, какао, шоколад, бобові, смажене м'ясо, риба",
        "restricted_foods": "кухонна сіль до 3—5 г на добу, рідина до 800—1000 мл, вершки, сметана, білки—до 140г",
        "recommended_foods": "супи вегетаріанські з овочів та круп, парові котлети з телятини або курятини, овочі варені, вінегрети, каші (гречана, вівсяна, манна), мед, варення, виноград, молоко, молочнокислі продукти, сири"
    },
    "Дієта № 7 а": {
        "indications": "гострий нефрит, загострення хронічного нефриту з виявленими змінами в осаді сечі",
        "purpose": "оберігання функцій нирок, нормалізуючий вплив на артеріальний тиск та набряки",
        "eating_regime": "дроблене харчування 5-7 разів на день. Протипоказані надто холодні та гарячі страви",
        "excluded_foods": "гострі блюда, м'ясний та рибний бульйони, прянощі, кава, какао, шоколад, бобові, смажене м'ясо, риба, кухонна сіль повністю",
        "restricted_foods": "рідина до 800-1000 мл, вершки, сметана, білки - до 50 г на добу",
        "recommended_foods": "супи вегетаріанські з овочів та круп, парові котлети з телятини або курятини, овочі варені, вінегрети, каші (гречана, вівсяна, манна), мед, варення, виноград, молоко, молочнокислі продукти, сири. Добова кількість харчових білків значно зменшується до 50 г, збільшується кількість вуглеводів."
    },
    "Дієта № 8": {
        "indications": "ожиріння при відсутності захворювань травного каналу, нирок, серцево-судинної системи",
        "purpose": "вплив на обмін речовин для запобігання або виключення надмірного відкладання жиру",
        "eating_regime": "часті прийоми малокалорійної їжі у достатньому обсязі, що усуває відчуття голоду. Загальна калорійність зменшується на 20—50 % (залежно від ступеня ожиріння та фізичної активності)",
        "excluded_foods": "жирні сорти м'яса, макаронні та борошняні вироби, тістечка, інші кондитерські вироби, варення, прянощі, гострі приправи, що збуджують апетит, кава, какао, шоколад",
        "restricted_foods": "кухонна сіль до 5—8 г на добу, введення рідини до 1000 мл, вершки, сметана, вершкове масло, картопля, каші (крім гречаної)",
        "recommended_foods": "вегетаріанські супи, багато варених та тушкованих овочів (кабачки, гарбузи, капуста, буряки, морква), молоко та молочнокислі продукти, знежирені сири, нежирні м'ясо та риба, гречана каша, фрукти та ягоди у сирому вигляді. Заправляти супи та каші слід рослинною олією, замість цукру вживати ксиліт, сорбіт."
    },
    "Дієта № 9": {
        "indications": "цукровий діабет",
        "purpose": "створення умов, що підтримують позитивний вуглеводний баланс, запобігання порушенням жирового та білкового обміну у хворого на цукровий діабет",
        "eating_regime": "приймати їжу слід 5—6 разів на день. Рослинні вуглеводи розподіляти на весь день, на вечерю або на ніч обов'язково слід випити склянку кефіру або ацидофільного молока з метою зменшення бродильних та гнильних процесів у кишках",
        "excluded_foods": "варення, солодкий чай, компоти, макаронні та різні кондитерські вироби",
        "restricted_foods": "картопля, бобові, солодкі фрукти (кавуни, виноград), кухонна сіль",
        "recommended_foods": "гречана каша, вегетаріанські супи, варені чи тушковані м'ясо, риба, молоко, кефір, знежирені сири, рослинна олія, варені яйця або омлет"
    },
    "Дієта № 10": {
        "indications": "захворювання серцево-судинної системи, ішемічна хвороба серця, природжені та ревматичні вади серця у період компенсації або недостатності кровообігу І ступеня, гіпертонічна хвороба І—II стадії, хронічний гломерулонефрит та пієлонефрит зі змінами в осаду сечі",
        "purpose": "створення сприятливих умов для кровообігу, запобігання утворенню набряків або сприяння усуненню вже існуючих набряків, покращання виділення азотистих речовин",
        "eating_regime": "приймати їжу 5—6 разів на день, вечеря має бути за 3 год. до сну",
        "excluded_foods": "жирні м'ясні та рибні страви, бульйони, смажене м'ясо, овочі, тістечка, торти, печінка, нирки, вим'я, сало, гострі страви, прянощі, різні консерви, какао, шоколад, кава",
        "restricted_foods": "кухонна сіль, рідина до 800—1000 мл на добу, щавель, шпинат, гриби",
        "recommended_foods": "супи круп'яні, овочеві, молочні, неміцний бульйон 1 раз на тиждень, парові котлети або тефтелі, варена телятина, курятина, вівсяна та гречана каші, овочеві салати та вінегрет, фрукти, ягоди, соки з них, вживання великої кількості рослинної олії"
    },
    "Дієта № 10 с": {
        "indications": "хвороби серця з недостатністю кровообігу II-III ступеня, інфаркт міокарда в гострій та підгострій стадіях, мозковий інсульт",
        "purpose": "за допомогою різкого обмеження вживання кухонної солі та збагачення дієти солями калію вплив на порушені функції серця, зменшення набряків, покращання функції нирок. Створення сприятливих умов для кровообігу, запобігання утворенню набряків або сприяння усуненню вже існуючих набряків, покращання виділення азотистих речовин",
        "eating_regime": "приймати їжу 5-6 разів на день, вечеря має бути за 3 год до сну",
        "excluded_foods": "повністю кухонна сіль, жирні м'ясні та рибні страви, бульйони, смажене м'ясо, овочі, тістечка, торти, печінка, нирки, вим'я, сало, гострі страви, прянощі, різні консерви, какао, шоколад, кава",
        "restricted_foods": "рідина до 800-1000 мл на добу, щавель, шпинат, гриби",
        "recommended_foods": "все у протертому вигляді, варене, парене, тушковане. Супи круп'яні, овочеві, молочні, неміцний бульйон 1 раз на тиждень, парові котлети або тефтелі, варена телятина, курятина, вівсяна та гречана каші, овочеві салати та вінегрет, фрукти, ягоди, соки з них, вживання великої кількості рослинної олії"
    },
    "Дієта № 10 а": {
        "indications": "атеросклероз судин з переважним ураженням судин серця, мозку, інфаркт міокарда у стадії рубцювання",
        "purpose": "запобігання подальшому розвитку атеросклеротичного процесу, при поєднанні атеросклерозу з ожирінням - зниження маси тіла. Створення сприятливих умов для кровообігу, запобігання утворенню набряків або сприяння усуненню вже існуючих набряків, покращання виділення азотистих речовин",
        "eating_regime": "приймати їжу 5-6 разів на день, вечеря має бути за 3 год до сну",
        "excluded_foods": "жирні м'ясні та рибні страви, бульйони, смажене м'ясо, овочі, тістечка, торти, печінка, нирки, вим'я, жирні сорти риби, сало, гострі страви, прянощі, різні консерви, какао, шоколад, кава",
        "restricted_foods": "кухонна сіль, рідина до 800-1000 мл на добу, щавель, шпинат, гриби. Особливо обмежуються продукти, багаті на холестерин",
        "recommended_foods": "продукти, що мають ліпотропну дію, овочі, фрукти, ягоди, соки з них, продукти моря з високим вмістом йоду (морська капуста, трепанги), рослинна олія, вівсяна, гречана каші. Супи круп'яні, овочеві, молочні, неміцний бульйон 1 раз на тиждень, парові котлети або тефтелі, варена телятина, курятина, овочеві салати та вінегрет"
    },
    "Дієта № 11": {
        "indications": "туберкульоз у стадії реконвалесценції (в умовах санаторію), виснаження організму після важких захворювань, у тому числі інфекційних, важка анемія, різні нагнійні процеси",
        "purpose": "підвищення опірності організму до туберкульозної інфекції, імунної реактивності організму, загальної опірності організму, посилення живлення організму, покращання білкового та вітамінного балансу",
        "eating_regime": "приймати їжу 5—6 разів на день з рівномірним (крім вечері) розподілом енергетичної цінності страв",
        "excluded_foods": "виключень та обмежень (крім алкоголю, кави) немає",
        "recommended_foods": "збільшена загальна енергетична цінність їжі до 16736 кДж (4000 ккал). Страви повинні вміщувати велику кількість білків тваринного походження, вітамінів; м'ясо, риба — у будь-якому вигляді, овочі, фрукти, соки, яйця, різноманітні молочні продукти. Для збудження апетиту можна давати прянощі"
    },
    "Дієта № 12": {
        "indications": "різні захворювання центральної та периферичної нервової системи",
        "purpose": "не подразнювати нервову систему",
        "recommended_foods": "морепродукти, нежирні кисломолочні продукти, крупи і макарони, овочі, фрукти, желе, соки, печиво, яйця",
        "excluded_foods": "цибуля, часник, шоколад, редька, щавель, чорний чай та кава, какао, алкоголь, гострі соуси та приправи, копченості",
        "general_characteristics": "дієта змішана, з обмеженням гострих страв, приправ, а також збуджуючих продуктів"
    },
    "Дієта № 13": {
        "indications": "інфекційні важкі захворювання, пневмонія в гострий гарячковий період, ангіна, гострий сепсис, післяопераційний стан",
        "purpose": "підтримання загального стану організму шляхом посиленого його живлення в гарячковий або післяопераційний період",
        "eating_regime": "дроблене харчування 6—8 разів на день, їжа може бути гарячою або теплою, при гіперпірексії — охолодженою. Якщо хворий знаходиться у важкому стані, вдень багато спить, то його годують, коли він прокидається, і навіть уночі",
        "excluded_foods": "смажені, гострі страви, жирні м'ясо, риба, сало, кава, алкогольні напої",
        "restricted_foods": "кухонна сіль до 8 г. на добу, овочі, що вміщують багато клітковини (капуста, буряки, редька)",
        "recommended_foods": "хворому дають багато рідини (до 2 л у вигляді соків, відвару шипшини, компотів). Страви мають бути рідкими або напіврідкими, неміцні рибні та м'ясні бульйони, хліб білий учорашньої випічки, білі сухарі, суп-пюре з каш на овочевому бульйоні, слизисті каші, не круто зварені яйця, молоко, вершки, сметана, кисломолочні продукти"
    },
    "Дієта № 14": {
        "indications": "фосфатурія з лужною реакцією сечі та випаданням осаду фосфорно-калієвих солей, сечокам'яна хвороба з фосфатними каменями",
        "purpose": "сприяти відновленню кислої реакції сечі, таким чином попереджаючи випадання осаду фосфатів",
        "eating_regime": "приймають їжу 4—5 разів на день. Дають багато рідини—до 1,5—2 л. Кулінарна обробка їжі звичайна",
        "restricted_foods": "масло, м'ясні та рибні супи",
        "excluded_foods": "молоко, сир, кава, какао, шоколад, бобові, міцні бульйони, продукти, щавель, шпинат, петрушка, агрус, прянощі, алкогольні напої",
        "recommended_foods": "фрукти, ягоди, соки з них, нежирні м'ясо, риба, гречана, вівсяна, рисова каші, мед, варення, мармелад"
    },
    "Дієта № 15": {
        "indications": "різні захворювання у період одужання при відсутності показань до призначення спеціальної лікувальної дієти та при нормальному стані органів травлення",
        "purpose": "в умовах лікувального закладу забезпечити харчування хворого за фізіологічними нормами",
        "eating_regime": "приймають їжу 4—5 разів на день",
        "excluded_foods": "жирне м'ясо (свинина, баранина), сало, тістечка, свіжий хліб",
        "restricted_foods": "гострі страви, прянощі, кава, какао, шоколад",
        "recommended_foods": "нежирне м'ясо, риба у будь-якій кулінарній обробці, різні молочні продукти, овочі, картопля у вигляді різних страв та гарнірів, частина овочів у сирому вигляді (салати), фрукти, ягоди, соки та компоти з них"
    },
    "Дієта № 0": {
        "indications": "3-5 доба після операцій на шлунково-кишковому тракті, захворювання центральної нервової системи з порушенням свідомості (порушення мозкового кровообігу, черепно-мозкова травма)",
        "purpose": "рідка малокалорійна дієта з обмеженням солі, включає легкозасвоювані продукти",
        "eating_regime": "режим харчування- кожні 2 години на протязі дня і ночі",
        "recommended_foods": "слизисті круп’яні відвари, легкий, м’ясний бульйон, фруктове желе, відвар шипшини, негазована мінеральна вода",
        "restricted_foods": "кухонна сіль",
    },
}
diet_data_en = {
    "Diet № 1": {
        "indications": "acute diseases of the upper parts of the alimentary canal, which last for 1-3 months, or chronic diseases that have worsened (esophagitis), gastritis with increased or normal acidity, duodenitis, peptic ulcer disease of the stomach and duodenum in the phase of moderate exacerbation.",
        "purpose": "Promoting the healing of stomach and duodenal ulcers, elimination of inflammatory processes in the upper parts of the alimentary canal.",
        "excluded_foods": "foods that remain in the stomach for a long time and irritate it (animal fats, vegetable fiber), stimulants of gastric secretion, spicy foods, spices, strong broths, mushrooms, legumes, coffee, chocolate, cocoa.",
        "restricted_foods": "table salt, lactic acid products.",
        "eating_regime": "The diet involves eating 6-7 times a day every 2-3 hours. ",
        "recommended_foods": "slimy soups from cereals (oat, buckwheat, rice, semolina), milk, cream, fresh low-fat sour cream, beef, veal, steamed fish cutlets, meatballs, mashed porridge, boiled eggs, pickled berries and fruits, diluted juices from them, bread "
    },
    "Diet № 1 a": {
        "indications": "exacerbation of peptic ulcer disease of the stomach and duodenum (first 3-7 days), exacerbation of gastritis with excessive acidity, burn of the esophagus or stomach",
        "purpose": "Facilitating the healing of stomach and duodenal ulcers, elimination of inflammatory processes in the upper parts of the digestive tract during an exacerbation",
        "excluded_foods": "foods that linger in the stomach for a long time and irritate it (animal fats, vegetable fiber), gastric secretion stimulants, spicy foods, spices, strong broths, mushrooms, legumes, coffee, chocolate, cocoa",
        "restricted_foods": "table salt, lactic acid products",
        "eating_regime": "The diet involves eating 6-7 times a day every 2-3 hours in small portions. ",
        "general_characteristics": "Dishes should be liquid or semi-liquid with reduced calorie content. ",
        "recommended_foods": "slimy soups from cereals (oat, buckwheat, rice, semolina), milk, cream, fresh low-fat sour cream, beef, veal, steamed fish cutlets, meatballs, mashed porridge, hard-boiled eggs, pickled berries and fruits, diluted juices from them "
    },
    "Diet № 1 b": {
        "indications": "exacerbation of peptic ulcer disease of the stomach and duodenum (first 10-20 days), exacerbation of chronic gastritis (first 7-10 days)",
        "purpose": "Facilitating the healing of stomach and duodenal ulcers, elimination of inflammatory processes in the upper parts of the digestive tract during an exacerbation",
        "excluded_foods": "foods that linger in the stomach for a long time and irritate it (animal fats, vegetable fiber), gastric secretion stimulants, spicy foods, spices, strong broths, mushrooms, legumes, coffee, chocolate, cocoa",
        "restricted_foods": "table salt, lactic acid products",
        "eating_regime": "The diet involves eating 6-7 times a day every 2-3 hours in small portions. ",
        "recommended_foods": "slimy soups from cereals (oat, buckwheat, rice, semolina), milk, cream, fresh low-fat sour cream, beef, veal, steamed fish cutlets, meatballs, mashed porridge, boiled eggs, pickled berries and fruits, diluted juices from them, bread "
    },
    "Diet № 2": {
        "indications": "acute gastritis with reduced acidity, chronic gastritis with reduced acidity in the exacerbation phase, the period of convalescence after enteritis, colitis",
        "purpose": "increasing gastric secretion, increasing the secretory activity of other digestive glands, improving the motor function of the stomach and intestines",
        "excluded_foods": "legumes, mushrooms, fatty meats (goose, duck, pork, lamb), fried dishes",
        "restricted_foods": "fresh milk, cream, sour cream, animal fat",
        "eating_regime": "crushed food 5-6 times a day",
        "recommended_foods": "yesterday's baked white bread, cereal soups (except millet) on low-fat meat or fish broth, boiled meat (beef, veal, chicken) and low-fat fish or steam cutlets or meatballs from them, boiled, stewed vegetables, "
    },
    "Diet № 3": {
        "indications": "chronic colitis in the period of exacerbation and remission with a tendency to constipation",
        "purpose": "strengthening of peristalsis of small and large intestines, regulation of bowel emptying process",
        "excluded_foods": "vegetables rich in essential oils (garlic, onion, radish, legumes), mushrooms",
        "restricted_foods": "pasta, dough products, cakes, fatty cheeses",
        "eating_regime": "crushed food 5-6 times a day, the main amount of food is given in the first half of the day, kefir is given on an empty stomach. ",
        "recommended_foods": "vegetables rich in vegetable fiber (cabbage, beets, carrots), rye bread made yesterday, cereal soups in vegetable, meat or fish broth, lean meat or fish (boiled, stewed, steamed), loose cereals (except "
    },
    "Diet № 4": {
        "indications": "acute enteritis, acute colitis, chronic enterocolitis, aggravated, dysentery in the acute period, accompanied by diarrhea",
        "purpose": "significant mechanical, chemical and thermal protection of the small and large intestines",
        "excluded_foods": "fresh milk, cream, sour cream, dried fruits, berries, juices from them, vegetables rich in vegetable fiber (cabbage, beets, carrots, sorrel), pasta",
        "restricted_foods": "sugar, jam, butter",
        "eating_regime": "crushed food 5-7 times a day. ",
        "recommended_foods": "crackers from white bread, soups on low-fat meat or fish broth with the addition of slimy broths (rice, oatmeal), slimy porridges (rice, oatmeal, buckwheat, semolina), steamed meat and fish meatballs, cutlets, boiled eggs, jelly"
    },
    "Diet № 4 a": {
        "indications": "chronic enterocolitis (especially in combination with chronic gastritis) in the period of decline of acute inflammatory phenomena, dysentery in the period of subsidence of acute inflammatory phenomena",
        "purpose": "significant mechanical, chemical and thermal protection of the small and large intestines",
        "excluded_foods": "fresh milk, cream, sour cream, dried fruits, berries, juices from them, vegetables rich in vegetable fiber (cabbage, beets, carrots, sorrel), pasta",
        "restricted_foods": "sugar, jam, butter",
        "eating_regime": "crushed food 5-7 times a day. ",
        "recommended_foods": "crackers from white bread, soups on low-fat meat or fish broth with the addition of slimy broths (rice, oatmeal), slimy porridges (rice, oatmeal, buckwheat, semolina), steamed meat and fish meatballs, cutlets, boiled eggs, jelly "
    },
    "Diet № 5": {
        "indications": "chronic hepatitis with a benign course and progressive viral hepatitis during the patient's recovery, liver cirrhosis in the compensation stage, acute hepatitis during the patient's recovery, chronic cholecystitis in the exacerbation stage, gallstone disease.",
        "purpose": "promoting the restoration of impaired liver functions, stimulating the processes of formation and secretion of bile",
        "excluded_foods": "fried and fatty dishes containing difficult-to-digest products of incomplete fat breakdown (acrolein and aldehydes), strong stimulators of gastric and pancreatic secretion (milk, coffee, cocoa, chocolate, mushrooms, sorrel, spinach, juices, berries, especially ",
        "eating_regime": "crushed food 5-6 times a day, the last meal no later than 3 hours. ",
        "recommended_foods": "a lot of sweet products (honey, jam, marmalade, marshmallows, pastila), white bread made yesterday, white bread crackers, vegetable soups, low-fat boiled meat or steam cutlets from it, low-fat boiled fish or steam cutlets "
    },
    "Diet № 5 a": {
        "indications": "acute cholecystitis, exacerbation of chronic cholecystitis, acute pancreatitis or exacerbation of chronic pancreatitis, chronic cholecystitis in combination with peptic ulcer disease of the stomach or duodenum. ",
        "purpose": "Helping to restore impaired functions of the liver and biliary tract, accumulation of glycogen in the liver, stimulation of bile secretion, limitation of mechanical irritation of the stomach and intestines.",
        "excluded_foods": "fried and fatty dishes containing difficult-to-digest products of incomplete fat breakdown (acrolein and aldehydes), strong stimulators of gastric and pancreatic secretion (milk, coffee, cocoa, chocolate, mushrooms, sorrel, spinach, juices, berries, especially ",
        "eating_regime": "Crushed food 5-6 times a day, the last meal no later than 3 hours before bedtime (preferably - kefir, acidophilic milk with low-fat cookies).",
        "recommended_foods": "A lot of sweet products (honey, jam, marmalade, marshmallows, pastila), white bread from yesterday's baking, white bread crackers, cereal soups on vegetable broth, dishes that are more mechanically chopped, a larger number of sweet dishes, eggs in the form of an omelet or souffle, "
    },
    "Diet № 6": {
        "indications": "gout, uric acid diathesis",
        "purpose": "promoting the normalization of purine metabolism and reducing the endogenous formation of uric acid",
        "excluded_foods": "animal fats, foods rich in purine compounds (lard, lamb, lard, liver, kidneys, sprats), strong broths, spinach, sorrel, legumes, chocolate, coffee, cocoa",
        "restricted_foods": "table salt",
        "eating_regime": "crushed food 5-6 times a day, administration of 2-2.5 liters of liquid (under diuresis control) - mainly in the form of tea, fruit and berry juices, alkaline water",
        "recommended_foods": "foods containing alkaline radicals (vegetables, especially cabbage, carrots, beets, fruits, berries, milk, rice, buckwheat, oatmeal, potatoes, except fried), honey, watermelons, melons, grapes, veal, boiled lean beef"
    },
    "Diet № 7": {
        "indications": "acute nephritis in the period of exacerbation, chronic nephritis with minor changes in the urine sediment, hypertensive disease with changes in the kidneys",
        "purpose": "protection of kidney functions, normalizing effect on blood pressure and edema",
        "eating_regime": "crushed food 5-7 times a day. ",
        "excluded_foods": "spicy dishes, meat and fish broths, spices, coffee, cocoa, chocolate, legumes, fried meat, fish",
        "restricted_foods": "table salt up to 3-5 g per day, liquid up to 800-1000 ml, cream, sour cream, proteins - up to 140 g",
        "recommended_foods": "vegetarian soups from vegetables and cereals, steam cutlets from veal or chicken, boiled vegetables, vinaigrettes, cereals (buckwheat, oat, semolina), honey, jam, grapes, milk, lactic acid products, cheeses"
    },
    "Diet № 7 a": {
        "indications": "acute nephritis, exacerbation of chronic nephritis with detected changes in urine sediment",
        "purpose": "protection of kidney functions, normalizing effect on blood pressure and edema",
        "eating_regime": "crushed food 5-7 times a day. ",
        "excluded_foods": "spicy dishes, meat and fish broths, spices, coffee, cocoa, chocolate, legumes, fried meat, fish, table salt completely",
        "restricted_foods": "liquid up to 800-1000 ml, cream, sour cream, proteins - up to 50 g per day",
        "recommended_foods": "vegetarian soups from vegetables and cereals, steam cutlets from veal or chicken, boiled vegetables, vinaigrettes, cereals (buckwheat, oat, semolina), honey, jam, grapes, milk, lactic acid products, cheeses. "
    },
    "Diet № 8": {
        "indications": "obesity in the absence of diseases of the digestive tract, kidneys, cardiovascular system",
        "purpose": "impact on metabolism to prevent or eliminate excessive fat deposition",
        "eating_regime": "frequent meals of low-calorie food in a sufficient amount, which eliminates the feeling of hunger. ",
        "excluded_foods": "fatty meats, pasta and flour products, cakes, other confectionery, jams, spices, spicy seasonings that stimulate the appetite, coffee, cocoa, chocolate",
        "restricted_foods": "table salt up to 5-8 g per day, fluid intake up to 1000 ml, cream, sour cream, butter, potatoes, porridge (except buckwheat)",
        "recommended_foods": "vegetarian soups, a lot of boiled and stewed vegetables (zucchini, pumpkins, cabbage, beets, carrots), milk and lactic acid products, low-fat cheeses, low-fat meat and fish, buckwheat porridge, fruits and berries in raw form. "
    },
    "Diet № 9": {
        "indications": "diabetes",
        "purpose": "creation of conditions that support a positive carbohydrate balance, prevention of disturbances in fat and protein metabolism in patients with diabetes",
        "eating_regime": "you should eat 5-6 times a day. ",
        "excluded_foods": "jam, sweet tea, compotes, macaroni and various confectionery products",
        "restricted_foods": "potatoes, legumes, sweet fruits (watermelons, grapes), table salt",
        "recommended_foods": "buckwheat porridge, vegetarian soups, boiled or stewed meat, fish, milk, kefir, low-fat cheeses, vegetable oil, boiled eggs or omelet"
    },
    "Diet № 10": {
        "indications": "diseases of the cardiovascular system, ischemic heart disease, congenital and rheumatic heart defects in the period of compensation or circulatory insufficiency of the first degree, hypertensive disease of the first and second stages, chronic glomerulonephritis and pyelonephritis with changes in the urine sediment",
        "purpose": "creating favorable conditions for blood circulation, preventing the formation of edema or promoting the elimination of already existing edema, improving the release of nitrogenous substances",
        "eating_regime": "eat 5-6 times a day, dinner should be in 3 hours. ",
        "excluded_foods": "fatty meat and fish dishes, broths, fried meat, vegetables, cakes, cakes, liver, kidneys, udder, lard, spicy dishes, spices, various preserves, cocoa, chocolate, coffee",
        "restricted_foods": "table salt, liquid up to 800-1000 ml per day, sorrel, spinach, mushrooms",
        "recommended_foods": "cereal, vegetable, milk soups, weak broth once a week, steam cutlets or meatballs, boiled veal, chicken, oatmeal and buckwheat porridge, vegetable salads and vinaigrette, fruits, berries, their juices, consumption of large amounts of vegetable oil"
    },
    "Diet № 10 c": {
        "indications": "heart disease with circulatory insufficiency of the II-III degree, myocardial infarction in the acute and subacute stages, cerebral stroke",
        "purpose": "by sharply limiting the use of table salt and enriching the diet with potassium salts, the effect on impaired heart functions, reduction of edema, improvement of kidney function. ",
        "eating_regime": "eat 5-6 times a day, dinner should be 3 hours before bedtime",
        "excluded_foods": "all table salt, fatty meat and fish dishes, broths, fried meat, vegetables, cakes, cakes, liver, kidneys, udder, lard, spicy dishes, spices, various preserves, cocoa, chocolate, coffee",
        "restricted_foods": "liquid up to 800-1000 ml per day, sorrel, spinach, mushrooms",
        "recommended_foods": "everything in pureed form, boiled, steamed, stewed. "
    },
    "Дієта № 10 a": {
        "indications": "atherosclerosis of vessels with predominant damage to vessels of the heart, brain, myocardial infarction in the stage of scarring",
        "purpose": "prevention of the further development of the atherosclerotic process, when atherosclerosis is combined with obesity - a decrease in body weight. ",
        "eating_regime": "eat 5-6 times a day, dinner should be 3 hours before bedtime",
        "excluded_foods": "fatty meat and fish dishes, broths, fried meat, vegetables, cakes, cakes, liver, kidneys, udder, fatty fish, lard, spicy dishes, spices, various preserves, cocoa, chocolate, coffee",
        "restricted_foods": "table salt, liquid up to 800-1000 ml per day, sorrel, spinach, mushrooms. ",
        "recommended_foods": "foods that have a lipotropic effect, vegetables, fruits, berries, juices from them, seafood with a high content of iodine (sea kale, trepang), vegetable oil, oatmeal, buckwheat porridge. "
    },
    "Diet № 11": {
        "indications": "tuberculosis in the stage of convalescence (in sanatorium conditions), exhaustion of the body after serious diseases, including infectious ones, severe anemia, various purulent processes",
        "purpose": "increasing the body's resistance to tuberculosis infection, the body's immune reactivity, the body's general resistance, strengthening the body's nutrition, improving the protein and vitamin balance",
        "eating_regime": "to eat 5-6 times a day with an even (except for dinner) distribution of the energy value of dishes",
        "excluded_foods": "there are no exceptions and restrictions (except for alcohol, coffee).",
        "recommended_foods": "increased total energy value of food to 16736 kJ (4000 kcal). "
    },
    "Diet № 12": {
        "indications": "various diseases of the central and peripheral nervous system",
        "purpose": "do not irritate the nervous system",
        "recommended_foods": "seafood, low-fat dairy products, cereals and pasta, vegetables, fruits, jelly, juices, cookies, eggs",
        "excluded_foods": "onion, garlic, chocolate, radish, sorrel, black tea and coffee, cocoa, alcohol, spicy sauces and seasonings, smoked meats",
        "general_characteristics": "the diet is mixed, with the restriction of spicy dishes, seasonings, as well as exciting products"
    },
    "Дієта № 13": {
        "indications": "severe infectious diseases, pneumonia in the acute febrile period, angina, acute sepsis, postoperative condition",
        "purpose": "maintenance of the general state of the body by means of enhanced nutrition during the febrile or postoperative period",
        "eating_regime": "crushed food 6-8 times a day, food can be hot or warm, in case of hyperpyrexia - cooled. ",
        "excluded_foods": "fried, spicy dishes, fatty meat, fish, lard, coffee, alcoholic beverages",
        "restricted_foods": "table salt up to 8 g per day, vegetables containing a lot of fiber (cabbage, beets, radishes)",
        "recommended_foods": "the patient is given a lot of liquid (up to 2 liters in the form of juices, rosehip decoction, compotes). "
    },
    "Diet № 14": {
        "indications": "phosphaturia with an alkaline reaction of urine and precipitation of phosphorus-potassium salts, urolithiasis with phosphate stones",
        "purpose": "contribute to the recovery of the acidic reaction of urine, thus preventing the precipitation of phosphate deposits",
        "eating_regime": "take food 4-5 times a day. ",
        "restricted_foods": "butter, meat and fish soups",
        "excluded_foods": "milk, cheese, coffee, cocoa, chocolate, legumes, strong broths, foods, sorrel, spinach, parsley, gooseberries, spices, alcoholic beverages",
        "recommended_foods": "fruits, berries, their juices, lean meat, fish, buckwheat, oatmeal, rice porridge, honey, jam, marmalade"
    },
    "Diet № 15": {
        "indications": "various diseases during the recovery period in the absence of indications for the appointment of a special therapeutic diet and in the normal state of the digestive organs",
        "purpose": "in the conditions of a medical institution, ensure the patient's nutrition according to physiological norms",
        "eating_regime": "take food 4-5 times a day",
        "excluded_foods": "fatty meat (pork, lamb), lard, cakes, fresh bread",
        "restricted_foods": "spicy dishes, spices, coffee, cocoa, chocolate",
        "recommended_foods": "lean meat, fish in any culinary processing, various dairy products, vegetables, potatoes in the form of various dishes and side dishes, part of vegetables in raw form (salads), fruits, berries, juices and compotes from them"
    },
    "Diet № 0": {
        "indications": "3-5 days after operations on the gastrointestinal tract, diseases of the central nervous system with impaired consciousness (impaired cerebral blood circulation, traumatic brain injury)",
        "purpose": "liquid low-calorie diet with salt restriction, includes easily digestible products",
        "eating_regime": "feeding regime - every 2 hours during the day and night",
        "recommended_foods": "slimy cereal broths, light, meat broth, fruit jelly, rosehip broth, non-carbonated mineral water",
        "restricted_foods": "table salt"
    }
}


def get_diet_data():
    return diet_data


def get_diet_data_en():
    return diet_data_en


def get_diet_data_list():
    return diet_data_list


def get_diet_data_list_en():
    return diet_data_list_en
